import { cn } from '../lib/utils'

const assetPath = (path: string) => `${import.meta.env.BASE_URL}${path.replace(/^\/+/, '')}`

// Brand badge: the nous-girl mark in the app-icon squircle (light variant).
// Ported from apps/desktop's BrandMark; the installer has no theme system so
// it always uses the light squircle asset. Generated by generate_icons.py.
export function BrandMark({ className, ...props }: React.ComponentProps<'span'>) {
  return (
    <span className={cn('inline-flex size-14 shrink-0 items-center justify-center', className)} {...props}>
      <img alt="" className="size-full object-contain" src={assetPath('nous-girl.png')} />
    </span>
  )
}
